### ISSUE TITLE
Compile for Linux

### ISSUE THREAD

**Issue by Parmjot-Singh** [Wyliemaster/GD-Decompiled#13]
Considering that RobTop said GD would be available fully for Linux at 2.2, I think it would be a good idea to get an early idea on what it would be like. I would help, but my laptop is fired and has gone for repairs, and I have school.

**Comment by SergeyMC9730** [comment]
where robtop said that

**Comment by Parmjot-Singh** [comment]
> where robtop said that

He said that he would look into it on Discord a few months back.

**Comment by SergeyMC9730** [comment]
> > where robtop said that
> 
> He said that he would look into it on Discord a few months back.

didn't found yet

**Comment by Parmjot-Singh** [comment]
> > > where robtop said that
> > 
> > He said that he would look into it on Discord a few months back.
> 
> didn't found yet

It's also been said on a recent AMA by RobTop.
![Screenshot_20220717-073917_Reddit.png](https://user-images.githubusercontent.com/100116708/179446968-3fd639f5-2e8b-4459-91a6-58e229d9e07f.png)

**Comment by SergeyMC9730** [comment]
oh ok. lets believe that robtop will eventually port GD on linux

**Comment by Wyliemaster** [comment]
Sorry, no plans to make it compile

**Comment by Parmjot-Singh** [comment]
All good, proton works fine

**Comment by SergeyMC9730** [comment]
Yea.
