### ISSUE TITLE
Compilation for older consoles

### ISSUE THREAD

**Issue by TechStudent10** [Wyliemaster/GD-Decompiled#18]
Would you think that it would be possible to recompile GD for an older console, say an N2DS/3DS?

**Comment by SergeyMC9730** [comment]
very hard task to do

**Comment by TechStudent10** [comment]
That wasn't my question. I was asking if it was possible. I really don't care if it's hard. I just want to know.

**Comment by SergeyMC9730** [comment]
Actually camila said to robtop that she could try to port GD to Wii a long time ago

**Comment by TechStudent10** [comment]
Interesting

**Comment by Wyliemaster** [comment]
There are no plans to make it possible to compile this. The intent of this project is reference material and nothing else.

If you're interested in a potential Port. [OpenGD](https://github.com/Open-GD/OpenGD) is probably the closest you'll get

**Comment by TechStudent10** [comment]
> There are no plans to make it possible to compile this. The intent of this project is reference material and nothing else.
> 
> If you're interested in a potential Port. [OpenGD](https://github.com/Open-GD/OpenGD) is probably the closest you'll get

Ah alright thanks. I've known about OpenGD for a bit now.
