### ISSUE TITLE
How to compile it.

### ISSUE THREAD

**Issue by TheEnderOfficial** [Wyliemaster/GD-Decompiled#2]
Hello, @Wyliemaster I delighted to you idea. But i\`m don\`t know how to compile it?

**Comment by Wyliemaster** [comment]
> Hello, @Wyliemaster I delighted to you idea. But i\`m don\`t know how to compile it?

I didn't set it up to be compiled, its here mainly for reference when people want to make mods. They can easily look at the code of the function they're hooking and then they can work with that
